import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';

const OpenSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={OpenSans.className} lang="en">
      <body className="flex flex-col w-full max-w-screen-2xl mx-auto">
        <header>
          <Navbar/>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
